- source/STAR.cpp
- source/bam_cat.c
- source/bam_cat.h
- source/sjSplitAlign.cpp
Include bam_cat.c since it's used in STAR.cpp.
Delete commented-out includes while we're here.
> Use header instead of extern for bam_cat

- source/STAR.cpp
It seems to compile either way? Most of the files here include GlobalVariables.h, so I think this may have been a typo.
> include GlobalVariables.h instead of .cpp

- source/Parameters.cpp
Sadly, our tool that will run rna-star always formats flags as 'parameter=value', e.g.
run-star --runThreadN=8
We can work around it or patch star locally to accept this argument style, but I think it does no harm to patch it upstream and might be useful to others.
> Support specifying command line parameters as key=value.

- source/Makefile
- source/htslib/Makefile
Please see commit comments for a more detailed explanation of why I added these changes.
Please note, that if the user does not specify any of these compiler related environment variables, the build will be exactly the same as it was before.
> improve the handling of compiler flags

- source/parametersDefault
*gen***e***omes* --> *genomes*
> fixed typo in sjdbGTFchrPrefix description

- source/STAR.cpp
- source/genomeGenerate.cpp
Hello,
here I am, starring at
<pre>
STAR --runThreadN 6 --runMode genomeGenerate --genomeDir genome --genomeFastaFiles genome/GRCh38.fasta --sjdbGTFfile genome/GRCh38.gtf
Feb 25 13:21:59 ..... Started STAR run
Feb 25 13:21:59 ... Starting to generate Genome files
Feb 25 13:23:31 ... starting to sort  Suffix Array. This may take a long time...
Feb 25 13:23:59 ... sorting Suffix Array chunks and saving them to disk...
</pre>
for a while now and, well, I presume I should be doing some else, but it kept nagging me that "Starting" is appearing both with a capital and a lower case S/s. I may be missing some higher semantics of that case issue, but though that you may possibly feel like deciding for an all lower-case scenario.
While I was at it, I found another "Starting", but this time with no …
> Helping the optical impression of status messages - just a tiny bit

- source/IncludeDefine.h
This patch was contributed by
Author: Jurica Stanojkovic <Jurica.Stanojkovic@imgtec.com>
Last-Changed: Fri, 3 Apr 2015 14:04:58 +0000
to address this particular bug reported
Bugs-Debian: http://bugs.debian.org/781828
to circumvent an issue in the glibc on the MIPSel platform.
> Fix compilation on MIPS - debian patch

- source/genomeScanFastaFiles.cpp
Hello,
another option would be that you accepted compressed .fasta files ;) I admit not have tried the numerical representation, just the character in my .gz file was nothign printable, hence the introduced single quotes. You certainly want to introduce the blank after the filename.
Cheers,
Steffen
> improved optics and clarity of error message

- source/SharedMemory.cpp
- source/SharedMemory.h
This patch fixes a bug in GetPosixObjectKey() that returned
a pointer to a c_str() for a string that went out of scope,
resulting in corruption of shm_() calls.
The new version of GetPosixObjectKey() returns the string itself,
and safely creates c_str() for in-scope calls.
> Fix memory corruption in GetPosixObjectKey()

- source/readLoad.cpp
We've recently had fastq files with a few zero length reads.  This commit allows STAR to skip over them without exiting
> Don't exit when fastq contains a zero-length read

- extras/docker/Dockerfile
Updating version number in the dockerfile to pull the most current release when building the image
> Bring Dockerfile up to date with current release

- source/ParametersSolo.cpp
- source/ParametersSolo.h
- source/SequenceFuns.cpp
- source/SequenceFuns.h
- source/SoloFeature_outputResults.cpp
- source/SoloReadBarcode.h
- source/SoloReadBarcode_getCBandUMI.cpp
Add support for cell barcodes which are longer than 16 nucleotides.
The old code overwrote the first nucleotides of the cell barcodes
with As for position 1 till (length cell barcode - 16) as cell
barcodes where converted with "convertNuclStrToInt32" and converted
back to "convertNuclInt32toString" and this would cause an overflow.
The number of barcodes is still limited to 2^32 after this patch.
UMIs are still limited to 16 nucleotides. Longer UMIs could be
supported in a similar way.
> Add support for cell barcodes which are longer than 16 nucleotides.

- source/ChimericAlign.h
- source/ChimericAlign_chimericJunctionOutput.cpp
- source/ChimericAlign_chimericStitching.cpp
- source/ChimericDetection.h
- source/ChimericDetection_chimericDetectionMult.cpp
- source/ReadAlign_chimericDetection.cpp
- source/ReadAlign_chimericDetectionPEmerged.cpp
- source/ReadAlign_mapOneRead.cpp
- source/ReadAlign_maxMappableLength2strands.cpp
- source/ReadAlign_stitchPieces.cpp
- source/SuffixArrayFuns.cpp
- source/Transcript.h
- source/Transcript_alignScore.cpp
- source/VERSION
The main thing that I did wrt chimera checking was to compare the alignment score of the chimeria to the best score of the non-chimeric alternative alignment.  If the non-chimeric alignment scored higher, then the chimera is excluded from reporting.  I included the score info in the chimeric.out.junction file so it's easy to track.  These additional fields include:
the maximum score possible (sum of read lengths)
the best non-chimeric alignment score
the chimeric alignment score for this chimeric alignment instance
the best chimeric alignment score across multimappers of this read
a flag indicating that the chimeric alignment was searched as a merged PE read or via the separate paired reads.
I also reorganized some of the logic around which chimeras to explore, pursuing the chimeric …
> chimeric alignment updates

- source/ChimericDetection_chimericDetectionMult.cpp
In STAR 2.7.2a, chimeric alignment candidates are not consistently checked for all score requirements, resulting in inclusion of some chimeric alignments that should be omitted.
>  Ensure chimeric alignment score requirements are consistently checked

- source/ChimericDetection_chimericDetectionMult.cpp
In 2.7.2a, there's a memory leak in handling chimeric multimappers, where low-scoring candidate chimeric alignments that are discarded do not have their memory deallocated. This issue predates 2.7.2a, but with recent updates, `chimericStitching`, where the memory is allocated, is called more frequently than previously, making the problem more visible, causing out of memory crashes even with 156GB of memory allotted for aligning human data.
On a test data set with single-threaded 2-pass mapping, I have verified that outputs are the same before and after patching. Specifically:
* Log.final.out mapping statistics are identical
* Chimeric.out.junction identical
* SJ.out.tab identical
* coordinate sorted BAM contents match using [BamUtil](https://genome.sph.umich.edu/wiki/BamUtil:_diff) to …
> Fix memory leak in handling chimeric multimappers.

- source/Genome_genomeGenerate.cpp
- source/STAR.cpp
1) If `nSA < saChunkSize`, `saChunkN` equals 0.
It leads to undefined behaviour here
```
uint* indPrefStart = new uint [0];
uint* indPrefChunkCount = new uint [0];
```
2) minor fix: parametersDefault is not null-terminated, 
and its length should be provided explicitly for `std::cout`.
> avoid undefined behaviour 

- extras/doc-latex/parametersDefault.tex
- source/parametersDefault
Super minor typo I noticed when I was going through the doc for the `readFilesPrefix` parameter.
> Fix `readFilesPrefix` docs preifx mispell

- source/SoloFeature_cellFiltering.cpp
I believe the `max` on line 20 should be a min, otherwise `nUMImin`
is almost _always_ simply determined by `nCB`, thus ignoring 
`pSolo.cellFilter.topCells`.
> Fix bug in `TopCells` mode in SoloFeature_cellFiltering.cpp

- source/BAMfunctions.cpp
- source/ChimericAlign.cpp
- source/ChimericAlign.h
- source/ChimericAlign_chimericBAMoutput.cpp
- source/ChimericDetection.h
- source/ChimericDetection_chimericDetectionMult.cpp
- source/Makefile
- source/ParametersChimeric_initialize.cpp
- source/ReadAlign.h
- source/ReadAlignChunk.cpp
- source/ReadAlign_alignBAM.cpp
- source/ReadAlign_chimericDetection.cpp
- source/ReadAlign_chimericDetectionOldOutput.cpp
- source/ReadAlign_chimericDetectionPEmerged.cpp
- source/ReadAlign_peOverlapMergeMap.cpp
- source/Transcript.h
Hi Alex,
This is a pull request which enables STAR to report multimapping chimeric reads in BAM format as discussed in issue #462.
The [SAM format specification](https://samtools.github.io/hts-specs/SAMv1.pdf) and [SAM tags specification](http://samtools.github.io/hts-specs/SAMtags.pdf) are not explicit on how to represent multimapping chimeric alignments. BWA reports them as secondary alignments without supplementary flag/tag. However, this has the major disadvantage that the supplementary nature of these alignments is not evident from the alignment record. Fusion detection tools that build on STAR would thus have a hard time extracting the relevant alignments. I contemplated what would be the best way and came up with the following:
* All supplementary chimeric alignments should be …
> report multi-mapping chimeric reads in BAM format

- source/Makefile
My first reflex was to have $(OBJECTS) removed, but OBJECTS also has many .cpp files. If those are not autogenerated, maybe have a separate variable for them?
Thanks!
Steffen
> Also cleaning opal/opal.o

- source/STAR.cpp
This is not really a PR since this needs to be adapted to your style and you may be aware of tools parsing that line. It is more an expression of despair on my side. STAR for me is wrapped by pigx-rnaseq. I got a bit into trouble with my local installation and now thought I should better have a look at the official guix-provided installation and am not fully confident that the STAR binary executed is the one I installed or the one that guix installed. The log file looks like
```
sh: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
/gnu/store/mmhimfwmmidf09jw1plw3aw1g1zn2nkh-bash-static-5.0.16/bin/sh: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
Feb 23 21:54:52 ..... started STAR run
Feb 23 21:54:57 ..... loading genome
EXITING: FATAL INPUT ERROR: …
```
> Show which STAR binary+version is executed

- source/Makefile
See https://reproducible-builds.org/docs/source-date-epoch/
> SOURCE_DATE_EPOCH to make the build more reproducible

- source/ReadAlign_peOverlapMergeMap.cpp
Hi Alex,
This pull request fixes #1135. The non-deterministic behavior/bug was caused by the following line:
https://github.com/alexdobin/STAR/blob/ffb66fb04e2642d1c2df87a31344552487ec491d/source/ReadAlign_peOverlapMergeMap.cpp#L332
Specifically, when the variable `ii` was `0`, the term `tempTrChim[ii-1]` accessed a negative index, which is invalid. I am surprised this did not produce segfaults. Somehow, it simply returned 0 in my tests, which leads to more or less random behavior, because the supplementary is assigned to mate1 or mate2 based on a meaningless criterion.
However, accessing a non-existent array index was not the only issue. The original code in the above line used the genomic mapping coordinate as a tie-breaker when there were two equally valid options for defining the …
> assign supplementary alignment to correct mate when mates fully overlap

- source/SoloCommon.h
Bug: https://bugs.gentoo.org/840586
> Add missing `#include <array>` (GCC 12)

- source/Genome.cpp
I recently ran into an issue where trying to `--genomeLoad LoadAndKeep` a genome would stall with the error message `"Another job is still loading the genome, sleeping for 1 min"` despite there being no other such job.
It turns out that in some circumstances, loading a genome after a different genome has previously been loaded
can fail due to the different genome directories hashing to the same `shmKey`. When this kind of collision happens, attempting to load genome B after genome A will never make it out of the `while` loop below because the comparison will be between the loaded size of genome A and the expected size of genome B:
https://github.com/alexdobin/STAR/blob/ffb66fb04e2642d1c2df87a31344552487ec491d/source/Genome_genomeLoad.cpp#L219
In the current code, the shmKey for a file …
> Increased entropy of shmKey to avoid collisions between genomes.

- source/parametersDefault
This PR makes minor parameters to the parametersDefault file. It assumes the following format:
```
<Argument name>       <default>
<type>: <short description>
<long description>
```
> standardise parameter format
